### ISSUE TITLE
Add long press in station list to update it

### ISSUE THREAD

**Issue by Dunky13** [Dunky13/RaspberryRadio#12]

**Comment by Dunky13** [comment]
Check line 71 of StationList - doesn't seem to work properly :/

**Comment by g1eb** [comment]
Where do you want to long click for the update to run?

This fails now because the layout is dynamically filled by the adapter with row items, which have a onLongClick listener on their own.

**Comment by Dunky13** [comment]
I'd say anywhere in the StationList, when longpressing it should update the stationlist whole
